name: Compile Main And Release
on:
  push:
    branches:
      - main
      - 'release/**'
jobs:
  compile-main-and-release:
    name: Compile Main And Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: src/
          args: ''
      - name: Set Environment Variables
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "ref_name=$(echo "$GITHUB_REF_NAME" | sed -e 's/\//-/g' -e 's/\./-/g')" >> "$GITHUB_ENV"
      - name: Rename PDF
        run: sudo mv out/main.pdf "out/${{ env.ref_name }}-${{ env.sha_short }}.pdf"
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.ref_name }}-${{ env.sha_short }}.pdf"
          path: "out/${{ env.ref_name }}-${{ env.sha_short }}.pdf"
